name: Re-entrenamiento diario del modelo

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  retrain-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Instalar dependencias
        run: pip install tensorflow firebase-admin numpy
      - name: Crear clave de servicio desde el secreto
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > serviceAccountKey.json
      - name: Ejecutar script de re-entrenamiento
        run: python retrain.py
      - name: Subir los nuevos pesos al repositorio
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add public/weights.json
          git diff --staged --quiet || git commit -m "Actualización automática de pesos del modelo"
          git push
